name: "parallel run"

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [service1, service2, service3]

    steps:
    - uses: actions/checkout@v2

    - name: Build ${{ matrix.service }}
      run: |
        chmod 755 ./${{ matrix.service }}/build-script.sh
        ./${{ matrix.service }}/build-script.sh ${{ matrix.service }}

    - name: Test ${{ matrix.service }}
      run: |
        chmod 755 ./${{ matrix.service }}/test-script.sh
        ./${{ matrix.service }}/test-script.sh ${{ matrix.service }}


